package vn.com.vng.stats.dashboard.model;

// Generated Sep 18, 2015 5:42:33 PM by Hibernate Tools 4.0.0


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Role generated by hbm2java
 */

public class Role {

    private Long id;
    private String name;
    private String description;

    public Role() {
    }

    public Role(long id, String name) {
        this.id = id;
        this.name = name;

    }

    public Role(long id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
